apiVersion: hive.openshift.io/v1alpha1
kind: SelectorSyncSet
metadata:
  generation: 1
  name: osd-operators-registry-catalogsource
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: "true"
  resourceApplyMode: sync
  resources:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      labels:
        opsrc-datastore: "true"
        opsrc-provider: redhat
      name: osd-operators-registry
      namespace: openshift-operator-lifecycle-manager
    spec:
      image: quay.io/openshift-sre/osd-operators-registry:master-d4ebb035581a85882f195d76775ce7eb
      displayName: OSD Operators
      icon:
        base64data: ""
        mediatype: ""
      publisher: Red Hat
      sourceType: grpc