apiVersion: hive.openshift.io/v1alpha1
kind: SelectorSyncSet
metadata:
  generation: 1
  name: osd-configure-alertmanager-operator
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: "true"
  resourceApplyMode: sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-monitoring
    annotations:
      openshift.io/node-selector: ""
    labels:
      openshift.io/cluster-monitoring: "true"
  - apiVersion: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    metadata:
      name: configure-alertmanager-operator
      namespace: openshift-monitoring
    spec:
      targetNamespaces:
      - openshift-monitoring
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: configure-alertmanager-operator
      namespace: openshift-monitoring
    spec:
      channel: master
      name: configure-alertmanager-operator
      source: osd-operators-registry
      sourceNamespace: openshift-operator-lifecycle-manager