apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: osd-operators-registry
  namespace: openshift-operator-lifecycle-manager
spec:
  image: quay.io/nmalik/osd-operators-registry:md5sum-version-8356135d304e4bfe976c9cd0d1170b74
  displayName: OSD Operators
  icon:
    base64data: ""
    mediatype: ""
  publisher: Red Hat
  sourceType: grpc