apiVersion: v1
kind: Namespace
metadata:
  name: configure-alertmanager-operator
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: configure-alertmanager-operator
  namespace: configure-alertmanager-operator
spec:
  targetNamespaces:
  - configure-alertmanager-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: configure-alertmanager-operator
  namespace: configure-alertmanager-operator
spec:
  channel: master
  name: configure-alertmanager-operator
  source: osd-operators-registry
  sourceNamespace: openshift-operator-lifecycle-manager
