apiVersion: v1
kind: Namespace
metadata:
  name: openshift-monitoring
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
spec:
  channel: master
  name: configure-alertmanager-operator
  source: osd-operators-registry
  sourceNamespace: openshift-operator-lifecycle-manager
