apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admin-operator
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
  - list
  - watch
